-- TAKITA SUSHI — banco, permissões, catálogo e pedidos
-- Execute este arquivo inteiro no SQL Editor de um projeto Supabase vazio.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

create table if not exists public.categories (
  id text primary key check (id ~ '^[a-z0-9-]+$'),
  name text not null check (char_length(name) between 2 and 60),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  category_id text not null references public.categories(id),
  description text not null default '' check (char_length(description) <= 500),
  price numeric(10,2) check (price is null or price >= 0),
  image_url text not null default '',
  active boolean not null default true,
  featured boolean not null default false,
  feature_tag text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id smallint primary key default 1 check (id = 1),
  store_name text not null default 'Takita Sushi',
  whatsapp_number text not null check (whatsapp_number ~ '^[0-9]{10,15}$'),
  pix_key text not null default '',
  credit_card_fee_percent numeric(5,2) not null default 0 check (credit_card_fee_percent between 0 and 100),
  is_open boolean not null default true,
  closed_message text not null default 'Estamos fechados no momento. Voltamos em breve!',
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated always as identity primary key,
  code text not null unique default ('TS-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8))),
  customer_name text not null,
  customer_phone text not null,
  customer_address text not null,
  customer_reference text not null default '',
  customer_location_url text not null default '',
  payment_method text not null check (payment_method in ('pix', 'cash', 'debit', 'credit')),
  customer_note text not null default '',
  subtotal numeric(10,2) not null default 0,
  fee numeric(10,2) not null default 0,
  total numeric(10,2) not null default 0,
  status text not null default 'awaiting_whatsapp' check (
    status in ('awaiting_whatsapp', 'whatsapp_opened', 'confirmed', 'preparing', 'out_for_delivery', 'completed', 'cancelled')
  ),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated always as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(10,2) not null,
  quantity integer not null check (quantity between 1 and 99),
  subtotal numeric(10,2) not null,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists settings_set_updated_at on public.store_settings;
create trigger settings_set_updated_at before update on public.store_settings
for each row execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_updated_at();

insert into public.categories (id, name, sort_order, active) values
  ('hot-holl', 'Hot Holl''s', 10, true),
  ('hossomaki', 'Uramakis e Hossomakis', 20, true),
  ('temaki', 'Temaki''s', 30, true),
  ('barca', 'Barcas', 40, true),
  ('bebidas', 'Bebidas', 50, true),
  ('adicionais', 'Adicionais', 60, true)
on conflict (id) do nothing;

insert into public.products
  (id, name, category_id, price, image_url, description, active, featured, feature_tag, sort_order)
values
  (1, 'Hot Holl Philadelphia', 'hot-holl', 30.00, 'imagens/salmão_hot.png', 'Porção de hot holl de salmão com finalização especial.', true, true, 'Mais pedido', 10),
  (2, 'Hot Holl Butterfly', 'hot-holl', 30.00, 'imagens/hotholl2.png', 'Porção de hot holl de camarão crocante e bem recheado.', true, false, '', 20),
  (3, 'Uramaki Salmão', 'hossomaki', 35.00, 'imagens/uramaki.png', 'Uramaki de salmão com 10 unidades.', true, false, '', 30),
  (4, 'Uramaki Camarão', 'hossomaki', 30.00, 'imagens/uramakicamarão.png', 'Uramaki de camarão com 10 unidades.', true, false, '', 40),
  (5, 'Hossomaki Salmão', 'hossomaki', 30.00, 'imagens/hossomaki.png', 'Hossomaki de salmão com 10 unidades.', true, false, '', 50),
  (6, 'Temaki Salmão Cru', 'temaki', 38.00, 'imagens/temaki (1).png', 'Temaki de salmão. 1 unidade.', true, true, 'Especial', 60),
  (7, 'Temaki Camarão Cru', 'temaki', 40.00, 'imagens/temakicamarão.png', 'Temaki de camarão. 1 unidade.', true, false, '', 70),
  (8, 'Dog-Hot Salmão', 'hot-holl', 38.00, 'imagens/dog.png', 'Dog-Hot de salmão. 1 unidade.', true, false, '', 80),
  (9, 'Dog-Hot Camarão', 'hot-holl', 38.00, 'imagens/dog.png', 'Dog-Hot de camarão. 1 unidade.', true, false, '', 90),
  (10, 'Temaki Salmão Hot', 'temaki', 40.00, 'imagens/temakihot.png', 'Temaki frito de salmão. 1 unidade.', true, false, '', 100),
  (11, 'Temaki Camarão Hot', 'temaki', 40.00, 'imagens/temaki3.png', 'Temaki frito de camarão. 1 unidade.', true, false, '', 110),
  (12, 'P Mista', 'barca', 60.00, 'imagens/barcaG.png', 'Barca mista com 20 unidades. Boa para um pedido menor.', true, false, '', 120),
  (13, 'M Mista', 'barca', 90.00, 'imagens/barcaG.png', 'Barca mista com 30 unidades. Ideal para dividir.', true, false, '', 130),
  (22, 'M Hot', 'barca', 90.00, 'imagens/barcaG.png', 'Barca hot com 30 unidades. Ideal para dividir.', true, false, '', 140),
  (14, 'G Mista', 'barca', 150.00, 'imagens/barcaG.png', 'Barca mista com 55 unidades. Boa para família, eventos e aniversários.', true, true, 'Destaque', 150),
  (15, 'G Hot', 'barca', 120.00, 'imagens/barcaG.png', 'Barca hot com 40 unidades. Boa para família, eventos e aniversários.', true, false, '', 160),
  (16, 'Coca-Cola 2L', 'bebidas', 15.00, 'imagens/coca.png', 'Refrigerante Coca-Cola. Garrafa de 2 litros.', true, false, '', 170),
  (17, 'Coca-Cola lata 350ml', 'bebidas', 6.00, 'imagens/cocalata.png', 'Refrigerante Coca-Cola. Lata de 350ml.', true, false, '', 180),
  (18, 'Molho Tarê', 'adicionais', 0.50, 'imagens/tare.png', 'Sachê de molho tarê adicional.', true, false, '', 190),
  (19, 'Molho Shoyu', 'adicionais', 0.50, 'imagens/shoyu.png', 'Sachê de shoyu adicional.', true, false, '', 200)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  greatest((select coalesce(max(id), 1) from public.products), 1),
  true
);

insert into public.store_settings
  (id, store_name, whatsapp_number, pix_key, credit_card_fee_percent, is_open, closed_message)
values
  (1, 'Takita Sushi', '5592985194693', '92985194693', 5, true, 'Estamos fechados no momento. Voltamos em breve!')
on conflict (id) do nothing;

alter table public.admin_users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.store_settings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- Permissões explícitas para projetos criados com
-- "Automatically expose new tables" desativado.
revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.categories from anon, authenticated;
revoke all on table public.products from anon, authenticated;
revoke all on table public.store_settings from anon, authenticated;
revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_items from anon, authenticated;

grant select on table public.categories to anon, authenticated;
grant select on table public.products to anon, authenticated;
grant select on table public.store_settings to anon, authenticated;

grant select on table public.admin_users to authenticated;
grant insert, update, delete on table public.categories to authenticated;
grant insert, update, delete on table public.products to authenticated;
grant update on table public.store_settings to authenticated;
grant select, update on table public.orders to authenticated;
grant select on table public.order_items to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;

drop policy if exists "admins can read own access" on public.admin_users;
create policy "admins can read own access" on public.admin_users
for select to authenticated using (user_id = auth.uid());

drop policy if exists "public reads active categories" on public.categories;
create policy "public reads active categories" on public.categories
for select to anon, authenticated using (active or public.is_admin());

drop policy if exists "admins manage categories" on public.categories;
create policy "admins manage categories" on public.categories
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public reads active products" on public.products;
create policy "public reads active products" on public.products
for select to anon, authenticated using (active or public.is_admin());

drop policy if exists "admins manage products" on public.products;
create policy "admins manage products" on public.products
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "public reads store settings" on public.store_settings;
create policy "public reads store settings" on public.store_settings
for select to anon, authenticated using (true);

drop policy if exists "admins manage store settings" on public.store_settings;
create policy "admins manage store settings" on public.store_settings
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins read orders" on public.orders;
create policy "admins read orders" on public.orders
for select to authenticated using (public.is_admin());

drop policy if exists "admins update orders" on public.orders;
create policy "admins update orders" on public.orders
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins read order items" on public.order_items;
create policy "admins read order items" on public.order_items
for select to authenticated using (public.is_admin());

create or replace function public.create_public_order(p_customer jsonb, p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_settings public.store_settings%rowtype;
  v_order public.orders%rowtype;
  v_product public.products%rowtype;
  v_item jsonb;
  v_quantity integer;
  v_product_id bigint;
  v_subtotal numeric(10,2) := 0;
  v_fee numeric(10,2) := 0;
  v_total numeric(10,2) := 0;
  v_result_items jsonb := '[]'::jsonb;
  v_payment_method text := trim(coalesce(p_customer->>'payment_method', ''));
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) < 1 or jsonb_array_length(p_items) > 50 then
    raise exception 'O pedido deve ter entre 1 e 50 itens.';
  end if;

  select * into strict v_settings from public.store_settings where id = 1;
  if not v_settings.is_open then
    raise exception '%', v_settings.closed_message;
  end if;

  if char_length(trim(coalesce(p_customer->>'name', ''))) not between 2 and 100 then
    raise exception 'Informe um nome válido.';
  end if;
  if char_length(trim(coalesce(p_customer->>'phone', ''))) not between 8 and 30 then
    raise exception 'Informe um telefone válido.';
  end if;
  if char_length(trim(coalesce(p_customer->>'address', ''))) not between 3 and 250 then
    raise exception 'Informe um endereço válido.';
  end if;
  if v_payment_method not in ('pix', 'cash', 'debit', 'credit') then
    raise exception 'Forma de pagamento inválida.';
  end if;

  insert into public.orders (
    customer_name, customer_phone, customer_address, customer_reference,
    customer_location_url, payment_method, customer_note
  ) values (
    left(trim(p_customer->>'name'), 100),
    left(trim(p_customer->>'phone'), 30),
    left(trim(p_customer->>'address'), 250),
    left(trim(coalesce(p_customer->>'reference', '')), 250),
    left(trim(coalesce(p_customer->>'location_url', '')), 500),
    v_payment_method,
    left(trim(coalesce(p_customer->>'note', '')), 1000)
  ) returning * into v_order;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    begin
      v_product_id := (v_item->>'product_id')::bigint;
      v_quantity := (v_item->>'quantity')::integer;
    exception when others then
      raise exception 'O pedido contém um item inválido.';
    end;

    if v_quantity < 1 or v_quantity > 99 then
      raise exception 'A quantidade de cada item deve estar entre 1 e 99.';
    end if;

    select * into v_product
    from public.products
    where id = v_product_id and active = true;

    if not found then
      raise exception 'Um produto foi removido ou está indisponível. Atualize o cardápio.';
    end if;
    if v_product.price is null then
      raise exception 'O produto % precisa de orçamento.', v_product.name;
    end if;

    insert into public.order_items (
      order_id, product_id, product_name, unit_price, quantity, subtotal
    ) values (
      v_order.id, v_product.id, v_product.name, v_product.price,
      v_quantity, round(v_product.price * v_quantity, 2)
    );

    v_subtotal := v_subtotal + round(v_product.price * v_quantity, 2);
    v_result_items := v_result_items || jsonb_build_array(jsonb_build_object(
      'product_id', v_product.id,
      'name', v_product.name,
      'unit_price', v_product.price,
      'quantity', v_quantity,
      'subtotal', round(v_product.price * v_quantity, 2)
    ));
  end loop;

  if v_payment_method = 'credit' then
    v_fee := round(v_subtotal * v_settings.credit_card_fee_percent / 100, 2);
  end if;
  v_total := v_subtotal + v_fee;

  update public.orders
  set subtotal = v_subtotal, fee = v_fee, total = v_total
  where id = v_order.id
  returning * into v_order;

  return jsonb_build_object(
    'id', v_order.id,
    'code', v_order.code,
    'items', v_result_items,
    'subtotal', v_subtotal,
    'fee', v_fee,
    'total', v_total,
    'settings', jsonb_build_object(
      'store_name', v_settings.store_name,
      'whatsapp_number', v_settings.whatsapp_number,
      'pix_key', v_settings.pix_key,
      'credit_card_fee_percent', v_settings.credit_card_fee_percent
    )
  );
end;
$$;

create or replace function public.mark_order_whatsapp_opened(p_order_code text)
returns void
language sql
security definer
set search_path = public
as $$
  update public.orders
  set status = 'whatsapp_opened'
  where code = p_order_code and status = 'awaiting_whatsapp';
$$;

revoke all on function public.create_public_order(jsonb, jsonb) from public;
grant execute on function public.create_public_order(jsonb, jsonb) to anon, authenticated;
revoke all on function public.mark_order_whatsapp_opened(text) from public;
grant execute on function public.mark_order_whatsapp_opened(text) to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images', 'product-images', true, 5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public reads product images" on storage.objects;
create policy "public reads product images" on storage.objects
for select to public using (bucket_id = 'product-images');

drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects
for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects
for update to authenticated using (bucket_id = 'product-images' and public.is_admin())
with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects
for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

-- ÚLTIMO PASSO DO PRIMEIRO ACESSO:
-- 1. Crie a conta do administrador em Authentication > Users.
-- 2. Troque o e-mail abaixo e execute apenas este comando:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'EMAIL_DO_ADMIN@EXEMPLO.COM'
-- on conflict (user_id) do nothing;

-- ATUALIZAÇÃO V2
-- Depois da primeira instalação, execute também o arquivo migration_v2.sql.
-- Ele adiciona acompanhamento público do pedido, arquivamento auditado,
-- custo dos produtos e relatórios sem apagar os dados existentes.
